import { 
  STORAGE_KEYS, 
  User, 
  Course, 
  Lesson, 
  Progress,
  Comment,
  Banner,
  Category,
  getFromStorage, 
  setToStorage 
} from './storage';

// Initial users
const initialUsers: User[] = [
  {
    id: 'admin-1',
    name: 'Administrador',
    email: 'admin@sistema.com',
    password: 'admin123',
    type: 'admin',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    bio: 'Administrador do sistema',
    active: true,
    createdAt: '2026-01-01',
  },
  {
    id: 'instructor-1',
    name: 'Ana Silva',
    email: 'instrutor@sistema.com',
    password: 'inst123',
    type: 'instructor',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=face',
    bio: 'Especialista em estratégias digitais e growth hacking. Mais de 10 anos de experiência no mercado.',
    instagram: '@anasilva',
    active: true,
    createdAt: '2026-01-05',
  },
  {
    id: 'instructor-2',
    name: 'Carlos Mendes',
    email: 'carlos@sistema.com',
    password: 'carlos123',
    type: 'instructor',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    bio: 'Mentor de negócios e especialista em automação de marketing.',
    instagram: '@carlosmendes',
    active: true,
    createdAt: '2026-01-08',
  },
  {
    id: 'user-1',
    name: 'João Santos',
    email: 'usuario@sistema.com',
    password: 'user123',
    type: 'user',
    avatar: 'https://images.unsplash.com/photo-1599566150163-29194dcabd36?w=150&h=150&fit=crop&crop=face',
    active: true,
    createdAt: '2026-01-15',
    unlockedCourses: ['course-1', 'course-2', 'course-3', 'course-5', 'course-6', 'hc-trilha-1', 'hc-trilha-2', 'hc-desafio-1', 'hc-desafio-2', 'hc-desafio-3', 'hc-material'],
  },
];

// Initial banners
const initialBanners: Banner[] = [
  {
    id: 'banner-1',
    title: 'Bem-vindo à Área de Membros',
    subtitle: 'Acesse frameworks exclusivos e transforme sua jornada',
    imageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1920&h=600&fit=crop',
    linkType: 'page',
    linkTo: '#courses',
    ctaText: 'Explorar Cursos',
    active: true,
    order: 1,
  },
  {
    id: 'banner-2',
    title: 'Novo Curso: Marketing Digital Avançado',
    subtitle: 'Aprenda estratégias que realmente funcionam',
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1920&h=600&fit=crop',
    linkType: 'course',
    linkTo: 'course-1',
    ctaText: 'Começar Agora',
    active: true,
    order: 2,
  },
  {
    id: 'banner-3',
    title: 'Promoção Especial',
    subtitle: 'Desbloqueie todos os cursos com desconto exclusivo',
    imageUrl: 'https://images.unsplash.com/photo-1553484771-047a44eee27b?w=1920&h=600&fit=crop',
    linkType: 'external',
    linkTo: '#',
    ctaText: 'Saiba Mais',
    active: true,
    order: 3,
  },
];

// Initial categories with Hoff Circle
const initialCategories: Category[] = [
  {
    id: 'cat-hoff-circle',
    name: 'Hoff Circle',
    icon: 'Target',
    description: 'Programa de Aceleração com trilhas de implementação',
    slug: 'hoff-circle',
    order: 0,
    active: true,
    hasDedicatedPage: true,
    showInMainMenu: true,
    pageConfig: {
      bannerTitle: 'Programa de Aceleração Hoff Circle',
      bannerSubtitle: '7 Trilhas de Implementação + 3 Desafios + Material Extra',
      bannerImageUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1920&h=600&fit=crop',
      bannerCtaText: 'Começar Jornada',
      aboutText: 'O Hoff Circle é um programa completo de aceleração projetado para transformar seu negócio. Com 7 trilhas de implementação sequenciais, 3 desafios opcionais e material extra exclusivo, você terá todas as ferramentas necessárias para alcançar resultados extraordinários.\n\nAs trilhas 1, 2 e 3 são os pilares fundamentais do método e devem ser completadas em sequência. Após concluir esses pilares, você terá acesso às trilhas complementares (4-7) que podem ser feitas em qualquer ordem.\n\nOs desafios são opcionais e estão sempre disponíveis para aprofundar seu aprendizado em áreas específicas.',
    },
    subcategories: [
      {
        id: 'subcat-trilhas',
        name: 'Trilhas de Implementação',
        slug: 'trilhas',
        description: 'Trilhas 1-3 são os pilares do método (sequenciais). Trilhas 4-7 são complementares.',
        order: 1,
        showRoadmap: true,
      },
      {
        id: 'subcat-desafios',
        name: 'Desafios',
        slug: 'desafios',
        description: 'Desafios opcionais para aprofundar seu aprendizado',
        order: 2,
        showRoadmap: false,
      },
      {
        id: 'subcat-material',
        name: 'Material Extra',
        slug: 'material-extra',
        description: 'Recursos complementares sempre disponíveis',
        order: 3,
        showRoadmap: false,
      },
    ],
  },
  {
    id: 'cat-1',
    name: 'Marketing Digital',
    icon: 'Megaphone',
    description: 'Cursos de marketing e publicidade digital',
    slug: 'marketing-digital',
    order: 1,
    active: true,
  },
  {
    id: 'cat-2',
    name: 'Vendas',
    icon: 'TrendingUp',
    description: 'Estratégias de vendas e conversão',
    slug: 'vendas',
    order: 2,
    active: true,
  },
  {
    id: 'cat-3',
    name: 'Estratégias',
    icon: 'Target',
    description: 'Frameworks estratégicos para seu negócio',
    slug: 'estrategias',
    order: 3,
    active: true,
  },
  {
    id: 'cat-4',
    name: 'Gestão',
    icon: 'Briefcase',
    description: 'Cursos de gestão e liderança',
    slug: 'gestao',
    order: 4,
    active: true,
  },
];

// Initial courses including Hoff Circle courses
const initialCourses: Course[] = [
  // === HOFF CIRCLE COURSES ===
  // Trilha 1 - Pilar 1 (Always available)
  {
    id: 'hc-trilha-1',
    title: 'Trilha 1 - Fundamentos',
    subtitle: 'PILAR 1 DO MÉTODO',
    description: 'O primeiro pilar do método Hoff Circle. Aprenda os fundamentos essenciais para construir uma base sólida.',
    thumbnail: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=1200&fit=crop',
    instructorId: 'instructor-1',
    category: 'Hoff Circle',
    categoryIds: ['cat-hoff-circle'],
    subcategoryId: 'subcat-trilhas',
    level: 'Iniciante',
    status: 'published',
    locked: false,
    totalDuration: '4:00:00',
    createdAt: '2026-01-01',
    modules: [
      {
        id: 'hc-t1-mod1',
        title: 'Introdução aos Fundamentos',
        description: 'Conceitos básicos do método',
        order: 1,
        lessonIds: ['hc-t1-l1', 'hc-t1-l2'],
      },
    ],
    sequenceConfig: {
      isSequential: true,
      position: 1,
      isPillar: true,
      requiresPrevious: false,
      prerequisiteCourseId: null,
      unlocksAfter: null,
    },
    roadmapConfig: {
      showInRoadmap: true,
      roadmapPosition: { x: 1, y: 1 },
      roadmapIcon: 'Flag',
      roadmapLabel: 'Pilar 1',
    },
  },
  // Trilha 2 - Pilar 2 (Requires T1)
  {
    id: 'hc-trilha-2',
    title: 'Trilha 2 - Estruturação',
    subtitle: 'PILAR 2 DO MÉTODO',
    description: 'O segundo pilar do método. Estruture seu negócio para crescimento sustentável.',
    thumbnail: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=1200&fit=crop',
    instructorId: 'instructor-1',
    category: 'Hoff Circle',
    categoryIds: ['cat-hoff-circle'],
    subcategoryId: 'subcat-trilhas',
    level: 'Intermediário',
    status: 'published',
    locked: false,
    totalDuration: '5:00:00',
    createdAt: '2026-01-02',
    modules: [
      {
        id: 'hc-t2-mod1',
        title: 'Estruturando o Negócio',
        description: 'Como estruturar para escalar',
        order: 1,
        lessonIds: ['hc-t2-l1', 'hc-t2-l2'],
      },
    ],
    sequenceConfig: {
      isSequential: true,
      position: 2,
      isPillar: true,
      requiresPrevious: true,
      prerequisiteCourseId: 'hc-trilha-1',
      unlocksAfter: 'hc-trilha-1',
    },
    roadmapConfig: {
      showInRoadmap: true,
      roadmapPosition: { x: 2, y: 1 },
      roadmapIcon: 'Flag',
      roadmapLabel: 'Pilar 2',
    },
  },
  // Trilha 3 - Pilar 3 (Requires T2)
  {
    id: 'hc-trilha-3',
    title: 'Trilha 3 - Escala',
    subtitle: 'PILAR 3 DO MÉTODO',
    description: 'O terceiro e último pilar fundamental. Escale seu negócio com estratégias comprovadas.',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=1200&fit=crop',
    instructorId: 'instructor-1',
    category: 'Hoff Circle',
    categoryIds: ['cat-hoff-circle'],
    subcategoryId: 'subcat-trilhas',
    level: 'Avançado',
    status: 'published',
    locked: false,
    totalDuration: '6:00:00',
    createdAt: '2026-01-03',
    modules: [
      {
        id: 'hc-t3-mod1',
        title: 'Estratégias de Escala',
        description: 'Escale com previsibilidade',
        order: 1,
        lessonIds: ['hc-t3-l1', 'hc-t3-l2'],
      },
    ],
    sequenceConfig: {
      isSequential: true,
      position: 3,
      isPillar: true,
      requiresPrevious: true,
      prerequisiteCourseId: 'hc-trilha-2',
      unlocksAfter: 'hc-trilha-2',
    },
    roadmapConfig: {
      showInRoadmap: true,
      roadmapPosition: { x: 3, y: 1 },
      roadmapIcon: 'Flag',
      roadmapLabel: 'Pilar 3',
    },
  },
  // Trilhas Complementares (4-7) - Require T3
  {
    id: 'hc-trilha-4',
    title: 'Trilha 4 - Automação',
    subtitle: 'TRILHA COMPLEMENTAR',
    description: 'Automatize processos e ganhe eficiência em todas as áreas do negócio.',
    thumbnail: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&h=1200&fit=crop',
    instructorId: 'instructor-2',
    category: 'Hoff Circle',
    categoryIds: ['cat-hoff-circle'],
    subcategoryId: 'subcat-trilhas',
    level: 'Intermediário',
    status: 'published',
    locked: false,
    totalDuration: '3:30:00',
    createdAt: '2026-01-04',
    modules: [
      {
        id: 'hc-t4-mod1',
        title: 'Automação Inteligente',
        description: 'Ferramentas e estratégias',
        order: 1,
        lessonIds: ['hc-t4-l1'],
      },
    ],
    sequenceConfig: {
      isSequential: false,
      position: 4,
      isPillar: false,
      requiresPrevious: true,
      prerequisiteCourseId: 'hc-trilha-3',
      unlocksAfter: 'hc-trilha-3',
    },
    roadmapConfig: {
      showInRoadmap: true,
      roadmapPosition: { x: 1, y: 2 },
      roadmapIcon: 'Star',
      roadmapLabel: 'Complementar',
    },
  },
  {
    id: 'hc-trilha-5',
    title: 'Trilha 5 - Tráfego',
    subtitle: 'TRILHA COMPLEMENTAR',
    description: 'Domine as estratégias de tráfego pago e orgânico para atrair clientes.',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=1200&fit=crop',
    instructorId: 'instructor-2',
    category: 'Hoff Circle',
    categoryIds: ['cat-hoff-circle'],
    subcategoryId: 'subcat-trilhas',
    level: 'Intermediário',
    status: 'published',
    locked: false,
    totalDuration: '4:00:00',
    createdAt: '2026-01-05',
    modules: [
      {
        id: 'hc-t5-mod1',
        title: 'Estratégias de Tráfego',
        description: 'Pago e orgânico',
        order: 1,
        lessonIds: ['hc-t5-l1'],
      },
    ],
    sequenceConfig: {
      isSequential: false,
      position: 5,
      isPillar: false,
      requiresPrevious: true,
      prerequisiteCourseId: 'hc-trilha-3',
      unlocksAfter: 'hc-trilha-3',
    },
    roadmapConfig: {
      showInRoadmap: true,
      roadmapPosition: { x: 2, y: 2 },
      roadmapIcon: 'Star',
      roadmapLabel: 'Complementar',
    },
  },
  {
    id: 'hc-trilha-6',
    title: 'Trilha 6 - Conversão',
    subtitle: 'TRILHA COMPLEMENTAR',
    description: 'Otimize seu funil de vendas e aumente suas taxas de conversão.',
    thumbnail: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&h=1200&fit=crop',
    instructorId: 'instructor-1',
    category: 'Hoff Circle',
    categoryIds: ['cat-hoff-circle'],
    subcategoryId: 'subcat-trilhas',
    level: 'Avançado',
    status: 'published',
    locked: false,
    totalDuration: '3:45:00',
    createdAt: '2026-01-06',
    modules: [
      {
        id: 'hc-t6-mod1',
        title: 'Otimização de Conversão',
        description: 'CRO na prática',
        order: 1,
        lessonIds: ['hc-t6-l1'],
      },
    ],
    sequenceConfig: {
      isSequential: false,
      position: 6,
      isPillar: false,
      requiresPrevious: true,
      prerequisiteCourseId: 'hc-trilha-3',
      unlocksAfter: 'hc-trilha-3',
    },
    roadmapConfig: {
      showInRoadmap: true,
      roadmapPosition: { x: 3, y: 2 },
      roadmapIcon: 'Star',
      roadmapLabel: 'Complementar',
    },
  },
  {
    id: 'hc-trilha-7',
    title: 'Trilha 7 - Retenção',
    subtitle: 'TRILHA COMPLEMENTAR',
    description: 'Estratégias avançadas de retenção e fidelização de clientes.',
    thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=1200&fit=crop',
    instructorId: 'instructor-1',
    category: 'Hoff Circle',
    categoryIds: ['cat-hoff-circle'],
    subcategoryId: 'subcat-trilhas',
    level: 'Avançado',
    status: 'published',
    locked: false,
    totalDuration: '3:15:00',
    createdAt: '2026-01-07',
    modules: [
      {
        id: 'hc-t7-mod1',
        title: 'Retenção e Fidelização',
        description: 'Clientes para sempre',
        order: 1,
        lessonIds: ['hc-t7-l1'],
      },
    ],
    sequenceConfig: {
      isSequential: false,
      position: 7,
      isPillar: false,
      requiresPrevious: true,
      prerequisiteCourseId: 'hc-trilha-3',
      unlocksAfter: 'hc-trilha-3',
    },
    roadmapConfig: {
      showInRoadmap: true,
      roadmapPosition: { x: 4, y: 2 },
      roadmapIcon: 'Star',
      roadmapLabel: 'Complementar',
    },
  },
  // Desafios (Always available)
  {
    id: 'hc-desafio-1',
    title: 'Desafio 1 - 7 Dias de Copy',
    subtitle: 'DESAFIO OPCIONAL',
    description: 'Desafio intensivo de 7 dias para dominar copywriting.',
    thumbnail: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&h=1200&fit=crop',
    instructorId: 'instructor-1',
    category: 'Hoff Circle',
    categoryIds: ['cat-hoff-circle'],
    subcategoryId: 'subcat-desafios',
    level: 'Iniciante',
    status: 'published',
    locked: false,
    totalDuration: '2:00:00',
    createdAt: '2026-01-08',
    modules: [
      {
        id: 'hc-d1-mod1',
        title: 'Desafio Copywriting',
        description: '7 dias de prática intensiva',
        order: 1,
        lessonIds: ['hc-d1-l1'],
      },
    ],
    sequenceConfig: {
      isSequential: false,
      position: 1,
      isPillar: false,
      requiresPrevious: false,
      prerequisiteCourseId: null,
      unlocksAfter: null,
    },
    roadmapConfig: {
      showInRoadmap: false,
      roadmapPosition: null,
      roadmapIcon: 'Trophy',
      roadmapLabel: 'Desafio',
    },
  },
  {
    id: 'hc-desafio-2',
    title: 'Desafio 2 - Produtividade',
    subtitle: 'DESAFIO OPCIONAL',
    description: 'Desafio de 21 dias para transformar sua produtividade.',
    thumbnail: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&h=1200&fit=crop',
    instructorId: 'instructor-2',
    category: 'Hoff Circle',
    categoryIds: ['cat-hoff-circle'],
    subcategoryId: 'subcat-desafios',
    level: 'Iniciante',
    status: 'published',
    locked: false,
    totalDuration: '3:00:00',
    createdAt: '2026-01-09',
    modules: [
      {
        id: 'hc-d2-mod1',
        title: 'Desafio Produtividade',
        description: '21 dias de transformação',
        order: 1,
        lessonIds: ['hc-d2-l1'],
      },
    ],
    sequenceConfig: {
      isSequential: false,
      position: 2,
      isPillar: false,
      requiresPrevious: false,
      prerequisiteCourseId: null,
      unlocksAfter: null,
    },
    roadmapConfig: {
      showInRoadmap: false,
      roadmapPosition: null,
      roadmapIcon: 'Trophy',
      roadmapLabel: 'Desafio',
    },
  },
  {
    id: 'hc-desafio-3',
    title: 'Desafio 3 - Vendas Express',
    subtitle: 'DESAFIO OPCIONAL',
    description: 'Desafio de 14 dias para fechar mais vendas.',
    thumbnail: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=1200&fit=crop',
    instructorId: 'instructor-1',
    category: 'Hoff Circle',
    categoryIds: ['cat-hoff-circle'],
    subcategoryId: 'subcat-desafios',
    level: 'Intermediário',
    status: 'published',
    locked: false,
    totalDuration: '2:30:00',
    createdAt: '2026-01-10',
    modules: [
      {
        id: 'hc-d3-mod1',
        title: 'Desafio Vendas',
        description: '14 dias intensivos',
        order: 1,
        lessonIds: ['hc-d3-l1'],
      },
    ],
    sequenceConfig: {
      isSequential: false,
      position: 3,
      isPillar: false,
      requiresPrevious: false,
      prerequisiteCourseId: null,
      unlocksAfter: null,
    },
    roadmapConfig: {
      showInRoadmap: false,
      roadmapPosition: null,
      roadmapIcon: 'Trophy',
      roadmapLabel: 'Desafio',
    },
  },
  // Material Extra (Always available)
  {
    id: 'hc-material',
    title: 'Material Extra',
    subtitle: 'RECURSOS COMPLEMENTARES',
    description: 'Acesse templates, planilhas e materiais exclusivos do programa.',
    thumbnail: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=1200&fit=crop',
    instructorId: 'instructor-1',
    category: 'Hoff Circle',
    categoryIds: ['cat-hoff-circle'],
    subcategoryId: 'subcat-material',
    level: 'Iniciante',
    status: 'published',
    locked: false,
    totalDuration: '1:00:00',
    createdAt: '2026-01-11',
    modules: [
      {
        id: 'hc-mat-mod1',
        title: 'Materiais e Templates',
        description: 'Recursos para download',
        order: 1,
        lessonIds: ['hc-mat-l1'],
      },
    ],
    sequenceConfig: {
      isSequential: false,
      position: 1,
      isPillar: false,
      requiresPrevious: false,
      prerequisiteCourseId: null,
      unlocksAfter: null,
    },
    roadmapConfig: {
      showInRoadmap: false,
      roadmapPosition: null,
      roadmapIcon: 'FileText',
      roadmapLabel: 'Material',
    },
  },
  // === EXISTING COURSES ===
  {
    id: 'course-1',
    title: 'Link{Mi}®',
    subtitle: 'ENTREGA EM UM CLIQUE',
    description: 'Aprenda a criar sistemas de entrega automatizados que convertem visitantes em clientes fiéis. Este framework completo vai te ensinar passo a passo como estruturar funis de alta conversão.',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=1200&fit=crop',
    instructorId: 'instructor-1',
    category: 'Estratégias',
    categoryIds: ['cat-1', 'cat-3'],
    level: 'Intermediário',
    status: 'published',
    locked: false,
    totalDuration: '5:30:00',
    createdAt: '2026-01-10',
    isNew: true,
    modules: [
      {
        id: 'mod-1-1',
        title: 'Fundamentos do Link{Mi}',
        description: 'Conceitos essenciais para dominar a metodologia',
        order: 1,
        lessonIds: ['lesson-1-1', 'lesson-1-2', 'lesson-1-3'],
      },
      {
        id: 'mod-1-2',
        title: 'Implementação Prática',
        description: 'Mão na massa: criando seu primeiro sistema',
        order: 2,
        lessonIds: ['lesson-1-4', 'lesson-1-5'],
      },
    ],
  },
  {
    id: 'course-2',
    title: 'Ative{Mi}®',
    subtitle: 'ATIVAÇÃO DE AUDIÊNCIA',
    description: 'Transforme seguidores passivos em uma comunidade engajada. Descubra as técnicas avançadas de ativação que grandes marcas utilizam para criar conexões autênticas.',
    thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=1200&fit=crop',
    instructorId: 'instructor-1',
    category: 'Engajamento',
    categoryIds: ['cat-1', 'cat-2'],
    level: 'Avançado',
    status: 'published',
    locked: false,
    totalDuration: '4:15:00',
    createdAt: '2026-01-12',
    modules: [
      {
        id: 'mod-2-1',
        title: 'Psicologia da Ativação',
        description: 'Entenda o que motiva sua audiência',
        order: 1,
        lessonIds: ['lesson-2-1', 'lesson-2-2'],
      },
      {
        id: 'mod-2-2',
        title: 'Estratégias de Conteúdo',
        description: 'Criando conteúdo que gera ação',
        order: 2,
        lessonIds: ['lesson-2-3', 'lesson-2-4'],
      },
    ],
  },
  {
    id: 'course-3',
    title: 'Scale{Mi}®',
    subtitle: 'ESCALE SEU NEGÓCIO',
    description: 'O framework definitivo para escalar seu negócio de forma sustentável. Aprenda os pilares da escalabilidade e como implementá-los na sua empresa.',
    thumbnail: 'https://images.unsplash.com/photo-1553484771-047a44eee27b?w=800&h=1200&fit=crop',
    instructorId: 'instructor-2',
    category: 'Negócios',
    categoryIds: ['cat-2', 'cat-4'],
    level: 'Avançado',
    status: 'published',
    locked: false,
    totalDuration: '6:45:00',
    createdAt: '2026-01-14',
    modules: [
      {
        id: 'mod-3-1',
        title: 'Mentalidade de Escala',
        description: 'Preparando-se para o crescimento exponencial',
        order: 1,
        lessonIds: ['lesson-3-1', 'lesson-3-2'],
      },
    ],
  },
  {
    id: 'course-4',
    title: 'Auto{Mi}®',
    subtitle: 'AUTOMAÇÃO INTELIGENTE',
    description: 'Automatize processos e libere seu tempo para o que realmente importa. Ferramentas e estratégias de automação para empreendedores.',
    thumbnail: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&h=1200&fit=crop',
    instructorId: 'instructor-2',
    category: 'Automação',
    categoryIds: ['cat-3', 'cat-4'],
    level: 'Iniciante',
    status: 'published',
    locked: true,
    totalDuration: '3:20:00',
    createdAt: '2026-01-16',
    modules: [
      {
        id: 'mod-4-1',
        title: 'Introdução à Automação',
        description: 'Por onde começar sua jornada de automação',
        order: 1,
        lessonIds: ['lesson-4-1'],
      },
    ],
  },
  {
    id: 'course-5',
    title: 'Growth{Mi}®',
    subtitle: 'CRESCIMENTO EXPONENCIAL',
    description: 'Estratégias de growth hacking para acelerar o crescimento do seu negócio digital.',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=1200&fit=crop',
    instructorId: 'instructor-1',
    category: 'Marketing',
    categoryIds: ['cat-1', 'cat-2'],
    level: 'Intermediário',
    status: 'published',
    locked: false,
    totalDuration: '4:00:00',
    createdAt: '2026-01-18',
    isNew: true,
    modules: [
      {
        id: 'mod-5-1',
        title: 'Fundamentos do Growth',
        description: 'Conceitos essenciais de growth hacking',
        order: 1,
        lessonIds: ['lesson-5-1', 'lesson-5-2'],
      },
    ],
  },
  {
    id: 'course-6',
    title: 'Lead{Mi}®',
    subtitle: 'GERAÇÃO DE LEADS',
    description: 'Aprenda a gerar leads qualificados de forma consistente e previsível.',
    thumbnail: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&h=1200&fit=crop',
    instructorId: 'instructor-2',
    category: 'Vendas',
    categoryIds: ['cat-2'],
    level: 'Iniciante',
    status: 'published',
    locked: false,
    totalDuration: '3:45:00',
    createdAt: '2026-01-20',
    modules: [
      {
        id: 'mod-6-1',
        title: 'Estratégias de Captação',
        description: 'Como atrair leads qualificados',
        order: 1,
        lessonIds: ['lesson-6-1'],
      },
    ],
  },
];

// Initial lessons including Hoff Circle lessons
const initialLessons: Lesson[] = [
  // Hoff Circle Lessons
  { id: 'hc-t1-l1', courseId: 'hc-trilha-1', moduleId: 'hc-t1-mod1', title: 'Introdução ao Método', description: 'Bem-vindo à Trilha 1', vimeoId: '76979871', duration: '15:00', order: 1, locked: false, resources: [] },
  { id: 'hc-t1-l2', courseId: 'hc-trilha-1', moduleId: 'hc-t1-mod1', title: 'Fundamentos Essenciais', description: 'Os pilares do método', vimeoId: '76979871', duration: '20:00', order: 2, locked: false, resources: [] },
  { id: 'hc-t2-l1', courseId: 'hc-trilha-2', moduleId: 'hc-t2-mod1', title: 'Estrutura de Negócio', description: 'Como estruturar para crescer', vimeoId: '76979871', duration: '25:00', order: 1, locked: false, resources: [] },
  { id: 'hc-t2-l2', courseId: 'hc-trilha-2', moduleId: 'hc-t2-mod1', title: 'Processos e Sistemas', description: 'Criando processos eficientes', vimeoId: '76979871', duration: '30:00', order: 2, locked: false, resources: [] },
  { id: 'hc-t3-l1', courseId: 'hc-trilha-3', moduleId: 'hc-t3-mod1', title: 'Escalando o Negócio', description: 'Estratégias de escala', vimeoId: '76979871', duration: '35:00', order: 1, locked: false, resources: [] },
  { id: 'hc-t3-l2', courseId: 'hc-trilha-3', moduleId: 'hc-t3-mod1', title: 'Crescimento Sustentável', description: 'Crescer com solidez', vimeoId: '76979871', duration: '40:00', order: 2, locked: false, resources: [] },
  { id: 'hc-t4-l1', courseId: 'hc-trilha-4', moduleId: 'hc-t4-mod1', title: 'Automação Avançada', description: 'Ferramentas de automação', vimeoId: '76979871', duration: '25:00', order: 1, locked: false, resources: [] },
  { id: 'hc-t5-l1', courseId: 'hc-trilha-5', moduleId: 'hc-t5-mod1', title: 'Tráfego Pago e Orgânico', description: 'Estratégias de tráfego', vimeoId: '76979871', duration: '30:00', order: 1, locked: false, resources: [] },
  { id: 'hc-t6-l1', courseId: 'hc-trilha-6', moduleId: 'hc-t6-mod1', title: 'CRO na Prática', description: 'Otimização de conversão', vimeoId: '76979871', duration: '28:00', order: 1, locked: false, resources: [] },
  { id: 'hc-t7-l1', courseId: 'hc-trilha-7', moduleId: 'hc-t7-mod1', title: 'Fidelizando Clientes', description: 'Estratégias de retenção', vimeoId: '76979871', duration: '25:00', order: 1, locked: false, resources: [] },
  { id: 'hc-d1-l1', courseId: 'hc-desafio-1', moduleId: 'hc-d1-mod1', title: 'Dia 1 - Copywriting', description: 'Início do desafio', vimeoId: '76979871', duration: '20:00', order: 1, locked: false, resources: [] },
  { id: 'hc-d2-l1', courseId: 'hc-desafio-2', moduleId: 'hc-d2-mod1', title: 'Dia 1 - Produtividade', description: 'Início do desafio', vimeoId: '76979871', duration: '15:00', order: 1, locked: false, resources: [] },
  { id: 'hc-d3-l1', courseId: 'hc-desafio-3', moduleId: 'hc-d3-mod1', title: 'Dia 1 - Vendas', description: 'Início do desafio', vimeoId: '76979871', duration: '18:00', order: 1, locked: false, resources: [] },
  { id: 'hc-mat-l1', courseId: 'hc-material', moduleId: 'hc-mat-mod1', title: 'Acesso aos Materiais', description: 'Downloads disponíveis', vimeoId: '76979871', duration: '10:00', order: 1, locked: false, resources: [{ type: 'pdf', name: 'Templates', url: '#' }] },
  // Existing lessons
  {
    id: 'lesson-1-1',
    courseId: 'course-1',
    moduleId: 'mod-1-1',
    title: 'Bem-vindo ao Link{Mi}®',
    description: 'Uma introdução completa ao framework Link{Mi} e como ele vai transformar sua forma de entregar valor aos clientes.',
    vimeoId: '76979871',
    duration: '12:30',
    order: 1,
    locked: false,
    resources: [
      { type: 'pdf', name: 'Slides da Aula', url: '#' },
      { type: 'link', name: 'Checklist de Implementação', url: '#' },
    ],
  },
  {
    id: 'lesson-1-2',
    courseId: 'course-1',
    moduleId: 'mod-1-1',
    title: 'Os 5 Pilares da Entrega',
    description: 'Descubra os 5 pilares fundamentais que sustentam qualquer sistema de entrega de alta performance.',
    vimeoId: '76979871',
    duration: '18:45',
    order: 2,
    locked: false,
    resources: [],
  },
  {
    id: 'lesson-1-3',
    courseId: 'course-1',
    moduleId: 'mod-1-1',
    title: 'Mapeando sua Jornada',
    description: 'Como mapear a jornada do cliente e identificar pontos de entrega estratégicos.',
    vimeoId: '76979871',
    duration: '22:10',
    order: 3,
    locked: false,
    resources: [
      { type: 'pdf', name: 'Template de Jornada', url: '#' },
    ],
  },
  {
    id: 'lesson-1-4',
    courseId: 'course-1',
    moduleId: 'mod-1-2',
    title: 'Criando seu Sistema',
    description: 'Passo a passo para criar seu primeiro sistema de entrega automatizado.',
    vimeoId: '76979871',
    duration: '35:00',
    order: 4,
    locked: false,
    resources: [],
  },
  {
    id: 'lesson-1-5',
    courseId: 'course-1',
    moduleId: 'mod-1-2',
    title: 'Otimização e Métricas',
    description: 'Como medir resultados e otimizar seu sistema para máxima conversão.',
    vimeoId: '76979871',
    duration: '28:15',
    order: 5,
    locked: false,
    resources: [],
  },
  {
    id: 'lesson-2-1',
    courseId: 'course-2',
    moduleId: 'mod-2-1',
    title: 'O Poder da Ativação',
    description: 'Entenda por que ativação é mais importante que crescimento de seguidores.',
    vimeoId: '76979871',
    duration: '15:00',
    order: 1,
    locked: false,
    resources: [],
  },
  {
    id: 'lesson-2-2',
    courseId: 'course-2',
    moduleId: 'mod-2-1',
    title: 'Gatilhos Mentais na Prática',
    description: 'Os gatilhos mentais mais eficazes para ativar sua audiência.',
    vimeoId: '76979871',
    duration: '20:30',
    order: 2,
    locked: false,
    resources: [],
  },
  {
    id: 'lesson-2-3',
    courseId: 'course-2',
    moduleId: 'mod-2-2',
    title: 'Conteúdo que Converte',
    description: 'Formatos de conteúdo com maior taxa de engajamento.',
    vimeoId: '76979871',
    duration: '25:00',
    order: 3,
    locked: false,
    resources: [],
  },
  {
    id: 'lesson-2-4',
    courseId: 'course-2',
    moduleId: 'mod-2-2',
    title: 'Calendário de Ativação',
    description: 'Como criar um calendário de conteúdo focado em ativação.',
    vimeoId: '76979871',
    duration: '18:00',
    order: 4,
    locked: false,
    resources: [],
  },
  {
    id: 'lesson-3-1',
    courseId: 'course-3',
    moduleId: 'mod-3-1',
    title: 'Mindset de Crescimento',
    description: 'A mentalidade necessária para escalar com sucesso.',
    vimeoId: '76979871',
    duration: '22:00',
    order: 1,
    locked: false,
    resources: [],
  },
  {
    id: 'lesson-3-2',
    courseId: 'course-3',
    moduleId: 'mod-3-1',
    title: 'Estruturando para Escala',
    description: 'Como estruturar sua empresa para crescimento sustentável.',
    vimeoId: '76979871',
    duration: '30:00',
    order: 2,
    locked: false,
    resources: [],
  },
  {
    id: 'lesson-4-1',
    courseId: 'course-4',
    moduleId: 'mod-4-1',
    title: 'Primeiros Passos na Automação',
    description: 'Introdução às ferramentas e conceitos de automação.',
    vimeoId: '76979871',
    duration: '16:00',
    order: 1,
    locked: false,
    resources: [],
  },
  {
    id: 'lesson-5-1',
    courseId: 'course-5',
    moduleId: 'mod-5-1',
    title: 'O que é Growth Hacking',
    description: 'Introdução aos conceitos e mentalidade do growth.',
    vimeoId: '76979871',
    duration: '18:00',
    order: 1,
    locked: false,
    resources: [],
  },
  {
    id: 'lesson-5-2',
    courseId: 'course-5',
    moduleId: 'mod-5-1',
    title: 'Experimentos de Crescimento',
    description: 'Como estruturar e executar experimentos de growth.',
    vimeoId: '76979871',
    duration: '24:00',
    order: 2,
    locked: false,
    resources: [],
  },
  {
    id: 'lesson-6-1',
    courseId: 'course-6',
    moduleId: 'mod-6-1',
    title: 'Fundamentos da Geração de Leads',
    description: 'Conceitos básicos para gerar leads de qualidade.',
    vimeoId: '76979871',
    duration: '20:00',
    order: 1,
    locked: false,
    resources: [],
  },
];

// Initial progress with Hoff Circle progress
const initialProgress: Progress[] = [
  {
    userId: 'user-1',
    courseId: 'course-1',
    completedLessons: ['lesson-1-1', 'lesson-1-2'],
    currentLesson: 'lesson-1-3',
    startedAt: '2026-01-20',
    lastAccessAt: '2026-01-23',
    progress: 40,
    liked: ['lesson-1-1'],
    disliked: [],
    favorites: ['lesson-1-2'],
  },
  {
    userId: 'user-1',
    courseId: 'course-2',
    completedLessons: ['lesson-2-1'],
    currentLesson: 'lesson-2-2',
    startedAt: '2026-01-21',
    lastAccessAt: '2026-01-23',
    progress: 25,
    liked: [],
    disliked: [],
    favorites: [],
  },
  // Hoff Circle Progress - Trilha 1 complete
  {
    userId: 'user-1',
    courseId: 'hc-trilha-1',
    completedLessons: ['hc-t1-l1', 'hc-t1-l2'],
    currentLesson: 'hc-t1-l2',
    startedAt: '2026-01-15',
    lastAccessAt: '2026-01-20',
    progress: 100,
    liked: ['hc-t1-l1'],
    disliked: [],
    favorites: [],
  },
  // Hoff Circle Progress - Trilha 2 in progress
  {
    userId: 'user-1',
    courseId: 'hc-trilha-2',
    completedLessons: ['hc-t2-l1'],
    currentLesson: 'hc-t2-l2',
    startedAt: '2026-01-20',
    lastAccessAt: '2026-01-23',
    progress: 50,
    liked: [],
    disliked: [],
    favorites: [],
  },
];

// Initial comments
const initialComments: Comment[] = [
  {
    id: 'comment-1',
    lessonId: 'lesson-1-1',
    userId: 'user-1',
    text: 'Excelente aula! Muito didática e fácil de entender.',
    createdAt: '2026-01-21T14:30:00Z',
    likes: 5,
  },
  {
    id: 'comment-2',
    lessonId: 'lesson-1-1',
    userId: 'instructor-1',
    text: 'Obrigada pelo feedback! Fico feliz que tenha gostado.',
    createdAt: '2026-01-21T15:00:00Z',
    likes: 2,
  },
];

// Seed function
export function seedData(): void {
  // Only seed if data doesn't exist
  const existingUsers = getFromStorage<User[]>(STORAGE_KEYS.USERS, []);
  
  if (existingUsers.length === 0) {
    setToStorage(STORAGE_KEYS.USERS, initialUsers);
    setToStorage(STORAGE_KEYS.COURSES, initialCourses);
    setToStorage(STORAGE_KEYS.LESSONS, initialLessons);
    setToStorage(STORAGE_KEYS.PROGRESS, initialProgress);
    setToStorage(STORAGE_KEYS.COMMENTS, initialComments);
    setToStorage(STORAGE_KEYS.BANNERS, initialBanners);
    setToStorage(STORAGE_KEYS.CATEGORIES, initialCategories);
    console.log('✅ Dados iniciais carregados com sucesso!');
  }
  
  // Always ensure banners and categories exist
  const existingBanners = getFromStorage<Banner[]>(STORAGE_KEYS.BANNERS, []);
  const existingCategories = getFromStorage<Category[]>(STORAGE_KEYS.CATEGORIES, []);
  
  if (existingBanners.length === 0) {
    setToStorage(STORAGE_KEYS.BANNERS, initialBanners);
  }
  if (existingCategories.length === 0) {
    setToStorage(STORAGE_KEYS.CATEGORIES, initialCategories);
  }
}

// Reset data function (for development)
export function resetData(): void {
  setToStorage(STORAGE_KEYS.USERS, initialUsers);
  setToStorage(STORAGE_KEYS.COURSES, initialCourses);
  setToStorage(STORAGE_KEYS.LESSONS, initialLessons);
  setToStorage(STORAGE_KEYS.PROGRESS, initialProgress);
  setToStorage(STORAGE_KEYS.COMMENTS, initialComments);
  setToStorage(STORAGE_KEYS.BANNERS, initialBanners);
  setToStorage(STORAGE_KEYS.CATEGORIES, initialCategories);
  console.log('🔄 Dados resetados com sucesso!');
}
